VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  if Vagrant.has_plugin?("vagrant-cachier")
    config.cache.scope = :box
  end

  # share networking-odl
  config.vm.synced_folder File.expand_path("../.."), "/home/vagrant/networking-odl"

  config.vm.box = "ubuntu/xenial64"
  # config.vm.box = "bento/ubuntu-16.04"
  config.vm.network 'private_network', ip: '192.168.0.10'
  config.vm.provision "shell", path: "setup-minimum.sh", privileged: true
  config.vm.provision "shell", path: "reproduce.sh", privileged: true

  # Increase the memory for the VM. If you need to run devstack, this needs
  # to be at least 8192
  config.vm.provider "virtualbox" do |v|
    v.memory = 8192
    v.cpus = 4
  end
end
