- project:
    templates:
      - openstack-python-jobs-neutron
      - openstack-python35-jobs-neutron
      - release-notes-jobs
      - periodic-stable-jobs-neutron
      - publish-openstack-sphinx-docs
      - check-requirements
    check:
      jobs:
        - networking-odl-rally-carbon:
            branches: ^(?!stable/newton).*$
            irrelevant-files:
              - ^.*\.rst$
              - ^doc/.*$
              - ^releasenotes/.*$
        - networking-odl-rally-nitrogen:
            branches: ^(?!stable/(newton|ocata)).*$
            irrelevant-files:
              - ^.*\.rst$
              - ^doc/.*$
              - ^releasenotes/.*$
        - openstack-tox-pep8:
            required-projects:
              - openstack/ceilometer
              - openstack/neutron-fwaas
              - openstack/neutron-lbaas
              - x/networking-l2gw
              - openstack/networking-sfc
              - openstack/networking-bgpvpn
        - openstack-tox-py27:
            required-projects:
              - openstack/ceilometer
              - openstack/neutron-fwaas
              - openstack/neutron-lbaas
              - x/networking-l2gw
              - openstack/networking-sfc
              - openstack/networking-bgpvpn
        - openstack-tox-py35:
            required-projects:
              - openstack/ceilometer
              - openstack/neutron-fwaas
              - openstack/neutron-lbaas
              - x/networking-l2gw
              - openstack/networking-sfc
              - openstack/networking-bgpvpn
        - openstack-tox-cover:
            required-projects:
              - openstack/ceilometer
              - openstack/neutron
              - openstack/neutron-fwaas
              - openstack/neutron-lbaas
              - x/networking-l2gw
              - openstack/networking-sfc
              - openstack/networking-bgpvpn
        - build-openstack-sphinx-docs:
            required-projects:
              - openstack/ceilometer
              - openstack/neutron-fwaas
              - openstack/neutron-lbaas
              - x/networking-l2gw
              - openstack/networking-sfc
              - openstack/networking-bgpvpn
        - requirements-check:
            nodeset: ubuntu-bionic
    gate:
      jobs:
        - networking-odl-rally-carbon:
            branches: ^(?!stable/newton).*$
            irrelevant-files:
              - ^.*\.rst$
              - ^doc/.*$
              - ^releasenotes/.*$
        - networking-odl-rally-nitrogen:
            branches: ^(?!stable/(newton|ocata)).*$
            irrelevant-files:
              - ^.*\.rst$
              - ^doc/.*$
              - ^releasenotes/.*$
        - openstack-tox-pep8:
            required-projects:
              - openstack/ceilometer
              - openstack/neutron-fwaas
              - openstack/neutron-lbaas
              - x/networking-l2gw
              - openstack/networking-sfc
              - openstack/networking-bgpvpn
        - openstack-tox-py27:
            required-projects:
              - openstack/ceilometer
              - openstack/neutron-fwaas
              - openstack/neutron-lbaas
              - x/networking-l2gw
              - openstack/networking-sfc
              - openstack/networking-bgpvpn
        - openstack-tox-py35:
            required-projects:
              - openstack/ceilometer
              - openstack/neutron-fwaas
              - openstack/neutron-lbaas
              - x/networking-l2gw
              - openstack/networking-sfc
              - openstack/networking-bgpvpn
        - openstack-tox-cover:
            required-projects:
              - openstack/ceilometer
              - openstack/neutron
              - openstack/neutron-fwaas
              - openstack/neutron-lbaas
              - x/networking-l2gw
              - openstack/networking-sfc
              - openstack/networking-bgpvpn
        - build-openstack-sphinx-docs:
            required-projects:
              - openstack/ceilometer
              - openstack/neutron-fwaas
              - openstack/neutron-lbaas
              - x/networking-l2gw
              - openstack/networking-sfc
              - openstack/networking-bgpvpn
        - requirements-check:
            nodeset: ubuntu-bionic
    post:
      jobs:
        - publish-openstack-python-branch-tarball:
            required-projects:
              - openstack/ceilometer
              - openstack/neutron-fwaas
              - openstack/neutron-lbaas
              - x/networking-l2gw
              - openstack/networking-sfc
              - openstack/networking-bgpvpn
    periodic-stable:
      jobs:
        - build-openstack-sphinx-docs:
            required-projects:
              - openstack/ceilometer
              - openstack/neutron-fwaas
              - openstack/neutron-lbaas
              - x/networking-l2gw
              - openstack/networking-sfc
              - openstack/networking-bgpvpn
        - openstack-tox-py27:
            required-projects:
              - openstack/ceilometer
              - openstack/neutron-fwaas
              - openstack/neutron-lbaas
              - x/networking-l2gw
              - openstack/networking-sfc
              - openstack/networking-bgpvpn
