- project:
    templates:
      - openstack-python-jobs-neutron
      - openstack-python35-jobs-neutron
      - release-notes-jobs
      - periodic-stable-jobs-neutron
      - publish-openstack-sphinx-docs
      - check-requirements
    check:
      jobs:
        - networking-odl-grenade-dsvm:
            voting: false
            branches: ^(?!(driverfixes|stable/(mitaka|newton))).*$
            irrelevant-files:
              - ^(test-|)requirements.txt$
              - ^.*\.rst$
              - ^doc/.*$
              - ^releasenotes/.*$
              - ^setup.cfg$
        - networking-odl-tempest-dsvm-boron-snapshot-v2driver:
            voting: false
            branches: ^(?!stable/newton).*$
            irrelevant-files:
              - ^(test-|)requirements.txt$
              - ^.*\.rst$
              - ^doc/.*$
              - ^releasenotes/.*$
              - ^setup.cfg$
        - networking-odl-tempest-dsvm-carbon-snapshot-vpnservice-v2driver:
            voting: false
            irrelevant-files:
              - ^(test-|)requirements.txt$
              - ^.*\.rst$
              - ^doc/.*$
              - ^releasenotes/.*$
              - ^setup.cfg$
        - networking-odl-tempest-dsvm-nitrogen-snapshot-vpnservice-v2driver:
            voting: false
            branches: ^(?!stable/(newton|ocata)).*$
            irrelevant-files:
              - ^(test-|)requirements.txt$
              - ^.*\.rst$
              - ^doc/.*$
              - ^releasenotes/.*$
              - ^setup.cfg$
        - networking-odl-tempest-dsvm-multinode-carbon-snapshot:
            voting: false
            irrelevant-files:
              - ^(test-|)requirements.txt$
              - ^.*\.rst$
              - ^doc/.*$
              - ^releasenotes/.*$
              - ^setup.cfg$
        - networking-odl-tempest-dsvm-multinode-nitrogen-snapshot:
            voting: false
            irrelevant-files:
              - ^(test-|)requirements.txt$
              - ^.*\.rst$
              - ^doc/.*$
              - ^releasenotes/.*$
              - ^setup.cfg$
        - networking-odl-rally-dsvm-carbon-snapshot:
            branches: ^(?!stable/newton).*$
            irrelevant-files:
              - ^.*\.rst$
              - ^doc/.*$
              - ^releasenotes/.*$
        - networking-odl-rally-dsvm-nitrogen-snapshot:
            branches: ^(?!stable/newton).*$
            irrelevant-files:
              - ^.*\.rst$
              - ^doc/.*$
              - ^releasenotes/.*$
        - networking-odl-dsvm-fullstack-carbon-snapshot:
            branches: ^(?!stable/(newton|ocata)).*$
            irrelevant-files:
              - ^.*\.rst$
              - ^doc/.*$
              - ^releasenotes/.*$
        - networking-odl-dsvm-functional-carbon-snapshot:
            branches: ^(?!stable/newton).*$
            irrelevant-files:
              - ^.*\.rst$
              - ^doc/.*$
              - ^releasenotes/.*$
        - networking-odl-dsvm-fullstack-nitrogen-snapshot:
            branches: ^(?!stable/(newton|ocata|pike)).*$
            irrelevant-files:
              - ^.*\.rst$
              - ^doc/.*$
              - ^releasenotes/.*$
        - networking-odl-dsvm-functional-nitrogen-snapshot:
            branches: ^(?!stable/(newton|ocata|pike)).*$
            irrelevant-files:
              - ^.*\.rst$
              - ^doc/.*$
              - ^releasenotes/.*$
        - openstack-tox-pep8:
            required-projects:
              - openstack/ceilometer
              - openstack/neutron-fwaas
              - openstack/neutron-lbaas
              - openstack/networking-l2gw
              - openstack/networking-sfc
              - openstack/networking-bgpvpn
        - openstack-tox-py27:
            required-projects:
              - openstack/ceilometer
              - openstack/neutron-fwaas
              - openstack/neutron-lbaas
              - openstack/networking-l2gw
              - openstack/networking-sfc
              - openstack/networking-bgpvpn
        - openstack-tox-py35:
            required-projects:
              - openstack/ceilometer
              - openstack/neutron-fwaas
              - openstack/neutron-lbaas
              - openstack/networking-l2gw
              - openstack/networking-sfc
              - openstack/networking-bgpvpn
        - openstack-tox-cover:
            required-projects:
              - openstack/ceilometer
              - openstack/neutron
              - openstack/neutron-fwaas
              - openstack/neutron-lbaas
              - openstack/networking-l2gw
              - openstack/networking-sfc
              - openstack/networking-bgpvpn
        - build-openstack-sphinx-docs:
            required-projects:
              - openstack/ceilometer
              - openstack/neutron-fwaas
              - openstack/neutron-lbaas
              - openstack/networking-l2gw
              - openstack/networking-sfc
              - openstack/networking-bgpvpn
    gate:
      jobs:
        - networking-odl-rally-dsvm-carbon-snapshot:
            branches: ^(?!stable/newton).*$
            irrelevant-files:
              - ^.*\.rst$
              - ^doc/.*$
              - ^releasenotes/.*$
        - networking-odl-rally-dsvm-nitrogen-snapshot:
            branches: ^(?!stable/newton).*$
            irrelevant-files:
              - ^.*\.rst$
              - ^doc/.*$
              - ^releasenotes/.*$
        - networking-odl-dsvm-fullstack-carbon-snapshot:
            branches: ^(?!stable/(newton|ocata)).*$
            irrelevant-files:
              - ^.*\.rst$
              - ^doc/.*$
              - ^releasenotes/.*$
        - networking-odl-dsvm-functional-carbon-snapshot:
            branches: ^(?!stable/newton).*$
            irrelevant-files:
              - ^.*\.rst$
              - ^doc/.*$
              - ^releasenotes/.*$
        - networking-odl-dsvm-fullstack-nitrogen-snapshot:
            branches: ^(?!stable/(newton|ocata|pike)).*$
            irrelevant-files:
              - ^.*\.rst$
              - ^doc/.*$
              - ^releasenotes/.*$
        - networking-odl-dsvm-functional-nitrogen-snapshot:
            branches: ^(?!stable/(newton|ocata|pike)).*$
            irrelevant-files:
              - ^.*\.rst$
              - ^doc/.*$
              - ^releasenotes/.*$
        - openstack-tox-pep8:
            required-projects:
              - openstack/ceilometer
              - openstack/neutron-fwaas
              - openstack/neutron-lbaas
              - openstack/networking-l2gw
              - openstack/networking-sfc
              - openstack/networking-bgpvpn
        - openstack-tox-py27:
            required-projects:
              - openstack/ceilometer
              - openstack/neutron-fwaas
              - openstack/neutron-lbaas
              - openstack/networking-l2gw
              - openstack/networking-sfc
              - openstack/networking-bgpvpn
        - openstack-tox-py35:
            required-projects:
              - openstack/ceilometer
              - openstack/neutron-fwaas
              - openstack/neutron-lbaas
              - openstack/networking-l2gw
              - openstack/networking-sfc
              - openstack/networking-bgpvpn
        - openstack-tox-cover:
            required-projects:
              - openstack/ceilometer
              - openstack/neutron
              - openstack/neutron-fwaas
              - openstack/neutron-lbaas
              - openstack/networking-l2gw
              - openstack/networking-sfc
              - openstack/networking-bgpvpn
        - build-openstack-sphinx-docs:
            required-projects:
              - openstack/ceilometer
              - openstack/neutron-fwaas
              - openstack/neutron-lbaas
              - openstack/networking-l2gw
              - openstack/networking-sfc
              - openstack/networking-bgpvpn
    post:
      jobs:
        - publish-openstack-python-branch-tarball:
            required-projects:
              - openstack/ceilometer
              - openstack/neutron-fwaas
              - openstack/neutron-lbaas
              - openstack/networking-l2gw
              - openstack/networking-sfc
              - openstack/networking-bgpvpn
    periodic-stable:
      jobs:
        - build-openstack-sphinx-docs:
            required-projects:
              - openstack/ceilometer
              - openstack/neutron-fwaas
              - openstack/neutron-lbaas
              - openstack/networking-l2gw
              - openstack/networking-sfc
              - openstack/networking-bgpvpn
        - openstack-tox-py27:
            required-projects:
              - openstack/ceilometer
              - openstack/neutron-fwaas
              - openstack/neutron-lbaas
              - openstack/networking-l2gw
              - openstack/networking-sfc
              - openstack/networking-bgpvpn

