- project:
    templates:
      - openstack-python-jobs-neutron
      - openstack-python35-jobs-neutron
      - release-notes-jobs
      - periodic-stable-jobs-neutron
      - publish-openstack-sphinx-docs
      - check-requirements
    check:
      jobs:
        - openstack-tox-pep8:
            required-projects:
              - openstack/ceilometer
              - openstack/neutron-fwaas
              - x/networking-l2gw
              - openstack/networking-sfc
              - openstack/networking-bgpvpn
        - openstack-tox-py27:
            required-projects:
              - openstack/ceilometer
              - openstack/neutron-fwaas
              - x/networking-l2gw
              - openstack/networking-sfc
              - openstack/networking-bgpvpn
        - openstack-tox-py35:
            required-projects:
              - openstack/ceilometer
              - openstack/neutron-fwaas
              - x/networking-l2gw
              - openstack/networking-sfc
              - openstack/networking-bgpvpn
        - openstack-tox-cover:
            required-projects:
              - openstack/ceilometer
              - openstack/neutron
              - openstack/neutron-fwaas
              - x/networking-l2gw
              - openstack/networking-sfc
              - openstack/networking-bgpvpn
        - build-openstack-sphinx-docs:
            required-projects:
              - openstack/ceilometer
              - openstack/neutron-fwaas
              - x/networking-l2gw
              - openstack/networking-sfc
              - openstack/networking-bgpvpn
        - requirements-check:
            nodeset: ubuntu-bionic
            voting: false
    gate:
      jobs:
        # Do not run non-voting jobs
        #- networking-odl-functional-oxygen
        #- networking-odl-functional-fluorine
        - openstack-tox-pep8:
            required-projects:
              - openstack/ceilometer
              - openstack/neutron-fwaas
              - x/networking-l2gw
              - openstack/networking-sfc
              - openstack/networking-bgpvpn
        - openstack-tox-py27:
            required-projects:
              - openstack/ceilometer
              - openstack/neutron-fwaas
              - x/networking-l2gw
              - openstack/networking-sfc
              - openstack/networking-bgpvpn
        - openstack-tox-py35:
            required-projects:
              - openstack/ceilometer
              - openstack/neutron-fwaas
              - x/networking-l2gw
              - openstack/networking-sfc
              - openstack/networking-bgpvpn
        - openstack-tox-cover:
            required-projects:
              - openstack/ceilometer
              - openstack/neutron
              - openstack/neutron-fwaas
              - x/networking-l2gw
              - openstack/networking-sfc
              - openstack/networking-bgpvpn
        - build-openstack-sphinx-docs:
            required-projects:
              - openstack/ceilometer
              - openstack/neutron-fwaas
              - x/networking-l2gw
              - openstack/networking-sfc
              - openstack/networking-bgpvpn
    post:
      jobs:
        - publish-openstack-python-branch-tarball:
            required-projects:
              - openstack/ceilometer
              - openstack/neutron-fwaas
              - x/networking-l2gw
              - openstack/networking-sfc
              - openstack/networking-bgpvpn
