- project:
    templates:
      - openstack-python-jobs-neutron
      - openstack-python35-jobs-neutron
      - openstack-python36-jobs-neutron
      - release-notes-jobs-python3
      - periodic-stable-jobs-neutron
      - publish-openstack-docs-pti
      - check-requirements
    check:
      jobs:
        - openstack-tox-pep8:
            required-projects:
              - openstack/ceilometer
              - openstack/neutron-fwaas
              - openstack/neutron-lbaas
              - openstack/networking-l2gw
              - openstack/networking-sfc
              - openstack/networking-bgpvpn
        - openstack-tox-cover:
            required-projects:
              - openstack/ceilometer
              - openstack/neutron
              - openstack/neutron-fwaas
              - openstack/neutron-lbaas
              - openstack/networking-l2gw
              - openstack/networking-sfc
              - openstack/networking-bgpvpn
        - openstack-tox-docs:
            required-projects:
              - openstack/ceilometer
              - openstack/neutron-fwaas
              - openstack/neutron-lbaas
              - openstack/networking-l2gw
              - openstack/networking-sfc
              - openstack/networking-bgpvpn
        - openstack-tox-lower-constraints:
            required-projects:
              - openstack/ceilometer
              - openstack/neutron
              - openstack/neutron-fwaas
              - openstack/neutron-lbaas
              - openstack/networking-l2gw
              - openstack/networking-sfc
              - openstack/networking-bgpvpn
        - openstack-tox-py27:
            required-projects:
              - openstack/ceilometer
              - openstack/neutron-fwaas
              - openstack/neutron-lbaas
              - openstack/networking-l2gw
              - openstack/networking-sfc
              - openstack/networking-bgpvpn
        - openstack-tox-py35:
            required-projects:
              - openstack/ceilometer
              - openstack/neutron-fwaas
              - openstack/neutron-lbaas
              - openstack/networking-l2gw
              - openstack/networking-sfc
              - openstack/networking-bgpvpn
        - openstack-tox-py36:
            required-projects:
              - openstack/ceilometer
              - openstack/neutron-fwaas
              - openstack/neutron-lbaas
              - openstack/networking-l2gw
              - openstack/networking-sfc
              - openstack/networking-bgpvpn
        - networking-odl-grenade:
            voting: false
            branches: ^(?!(driverfixes|stable/(mitaka|newton))).*$
            irrelevant-files:
              - ^(test-|)requirements.txt$
              - ^.*\.rst$
              - ^doc/.*$
              - ^releasenotes/.*$
              - ^setup.cfg$
        - networking-odl-tempest-oxygen
        - networking-odl-tempest-fluorine
        - networking-odl-tempest-oxygen-multinode:
            voting: false
            irrelevant-files:
              - ^(test-|)requirements.txt$
              - ^.*\.rst$
              - ^doc/.*$
              - ^releasenotes/.*$
              - ^setup.cfg$
        - networking-odl-tempest-fluorine-multinode:
            voting: false
            irrelevant-files:
              - ^(test-|)requirements.txt$
              - ^.*\.rst$
              - ^doc/.*$
              - ^releasenotes/.*$
              - ^setup.cfg$
        - networking-odl-rally-oxygen:
            voting: false
            branches: ^(?!stable/(newton|ocata|pike)).*$
            irrelevant-files:
              - ^.*\.rst$
              - ^doc/.*$
              - ^releasenotes/.*$
        - networking-odl-rally-fluorine:
            voting: false
            branches: ^(?!stable/(newton|ocata|pike)).*$
            irrelevant-files:
              - ^.*\.rst$
              - ^doc/.*$
              - ^releasenotes/.*$
        - networking-odl-functional-oxygen
        - networking-odl-functional-fluorine
    gate:
      jobs:
        - openstack-tox-pep8:
            required-projects:
              - openstack/ceilometer
              - openstack/neutron-fwaas
              - openstack/neutron-lbaas
              - openstack/networking-l2gw
              - openstack/networking-sfc
              - openstack/networking-bgpvpn
        - openstack-tox-docs:
            required-projects:
              - openstack/ceilometer
              - openstack/neutron-fwaas
              - openstack/neutron-lbaas
              - openstack/networking-l2gw
              - openstack/networking-sfc
              - openstack/networking-bgpvpn
        - openstack-tox-lower-constraints:
            required-projects:
              - openstack/ceilometer
              - openstack/neutron
              - openstack/neutron-fwaas
              - openstack/neutron-lbaas
              - openstack/networking-l2gw
              - openstack/networking-sfc
              - openstack/networking-bgpvpn
        - openstack-tox-py27:
            required-projects:
              - openstack/ceilometer
              - openstack/neutron-fwaas
              - openstack/neutron-lbaas
              - openstack/networking-l2gw
              - openstack/networking-sfc
              - openstack/networking-bgpvpn
        - openstack-tox-py35:
            required-projects:
              - openstack/ceilometer
              - openstack/neutron-fwaas
              - openstack/neutron-lbaas
              - openstack/networking-l2gw
              - openstack/networking-sfc
              - openstack/networking-bgpvpn
        - openstack-tox-py36:
            required-projects:
              - openstack/ceilometer
              - openstack/neutron-fwaas
              - openstack/neutron-lbaas
              - openstack/networking-l2gw
              - openstack/networking-sfc
              - openstack/networking-bgpvpn
        - networking-odl-functional-oxygen
        - networking-odl-functional-fluorine
