- project:
    templates:
      - openstack-python3-jobs-neutron
      - release-notes-jobs-python3
      - periodic-stable-jobs-neutron
      - publish-openstack-docs-pti
      - check-requirements
    check:
      jobs:
        - openstack-tox-pep8:
            required-projects: &odl_doc_required_projects
              - openstack/ceilometer
              - x/networking-l2gw
              - openstack/networking-sfc
              - openstack/networking-bgpvpn
        - openstack-tox-cover:
            required-projects: &odl_required_projects
              - openstack/ceilometer
              - openstack/neutron
              - x/networking-l2gw
              - openstack/networking-sfc
              - openstack/networking-bgpvpn
        - openstack-tox-docs:
            required-projects: *odl_doc_required_projects
        - openstack-tox-py38:
            required-projects: *odl_required_projects
        - openstack-tox-py39:
            required-projects: *odl_required_projects
        - openstack-tox-py310:
            required-projects: *odl_required_projects
        - networking-odl-grenade:
            voting: false
            irrelevant-files:
              - ^(test-|)requirements.txt$
              - ^.*\.rst$
              - ^doc/.*$
              - ^releasenotes/.*$
              - ^setup.cfg$
        - networking-odl-tempest-neon
        - networking-odl-tempest-sodium
        - networking-odl-tempest-neon-multinode:
            voting: false
        - networking-odl-tempest-sodium-multinode:
            voting: false
        - networking-odl-rally-neon:
            voting: false
            irrelevant-files:
              - ^.*\.rst$
              - ^doc/.*$
              - ^releasenotes/.*$
        - networking-odl-rally-sodium:
            voting: false
            irrelevant-files:
              - ^.*\.rst$
              - ^doc/.*$
              - ^releasenotes/.*$
        - networking-odl-functional-neon:
            required-projects: *odl_required_projects
        - networking-odl-functional-sodium:
            required-projects: *odl_required_projects
    gate:
      jobs:
        - openstack-tox-pep8:
            required-projects: *odl_doc_required_projects
        - openstack-tox-docs:
            required-projects: *odl_doc_required_projects
        - openstack-tox-py38:
            required-projects: *odl_required_projects
        - openstack-tox-py39:
            required-projects: *odl_required_projects
        - openstack-tox-py310:
            required-projects: *odl_required_projects
        - networking-odl-functional-neon:
            required-projects: *odl_required_projects
        - networking-odl-functional-sodium:
            required-projects: *odl_required_projects
    periodic-weekly:
      jobs:
        - openstack-tox-py39
        - networking-odl-functional-sodium
