- project:
    templates:
      - openstack-python3-yoga-jobs-neutron
      - release-notes-jobs-python3
      - periodic-stable-jobs-neutron
      - publish-openstack-docs-pti
      - check-requirements
    check:
      jobs:
        - openstack-tox-pep8:
            required-projects:
              - openstack/ceilometer
              - x/networking-l2gw
              - openstack/networking-sfc
              - openstack/networking-bgpvpn
        - openstack-tox-cover:
            required-projects:
              - openstack/ceilometer
              - openstack/neutron
              - x/networking-l2gw
              - openstack/networking-sfc
              - openstack/networking-bgpvpn
        - openstack-tox-docs:
            required-projects:
              - openstack/ceilometer
              - x/networking-l2gw
              - openstack/networking-sfc
              - openstack/networking-bgpvpn
        - openstack-tox-lower-constraints:
            voting: false
            required-projects:
              - openstack/ceilometer
              - openstack/neutron
              - x/networking-l2gw
              - openstack/networking-sfc
              - openstack/networking-bgpvpn
        - openstack-tox-py36:
            required-projects:
              - openstack/ceilometer
              - x/networking-l2gw
              - openstack/networking-sfc
              - openstack/networking-bgpvpn
        - networking-odl-grenade:
            voting: false
            irrelevant-files:
              - ^(test-|)requirements.txt$
              - ^.*\.rst$
              - ^doc/.*$
              - ^releasenotes/.*$
              - ^setup.cfg$
        - networking-odl-tempest-neon
        - networking-odl-tempest-sodium
        - networking-odl-tempest-neon-multinode:
            voting: false
        - networking-odl-tempest-sodium-multinode:
            voting: false
        - networking-odl-rally-neon:
            voting: false
            irrelevant-files:
              - ^.*\.rst$
              - ^doc/.*$
              - ^releasenotes/.*$
        - networking-odl-rally-sodium:
            voting: false
            irrelevant-files:
              - ^.*\.rst$
              - ^doc/.*$
              - ^releasenotes/.*$
        - networking-odl-functional-neon
        - networking-odl-functional-sodium
    gate:
      jobs:
        - openstack-tox-pep8:
            required-projects:
              - openstack/ceilometer
              - x/networking-l2gw
              - openstack/networking-sfc
              - openstack/networking-bgpvpn
        - openstack-tox-docs:
            required-projects:
              - openstack/ceilometer
              - x/networking-l2gw
              - openstack/networking-sfc
              - openstack/networking-bgpvpn
        - openstack-tox-py36:
            required-projects:
              - openstack/ceilometer
              - x/networking-l2gw
              - openstack/networking-sfc
              - openstack/networking-bgpvpn
        - networking-odl-functional-neon
        - networking-odl-functional-sodium
