- project:
    templates:
      - openstack-python3-zed-jobs-neutron
      - release-notes-jobs-python3
      - periodic-stable-jobs-neutron
      - publish-openstack-docs-pti
      - check-requirements
    check:
      jobs:
        - openstack-tox-pep8:
            required-projects: &odl_doc_required_projects
              - name: openstack/ceilometer
                override-checkout: stable/zed
              - name: x/networking-l2gw
                override-checkout: stable/wallaby
              - name: openstack/networking-sfc
                override-checkout: stable/zed
              - name: openstack/networking-bgpvpn
                override-checkout: stable/zed
        - openstack-tox-cover:
            required-projects: &odl_required_projects
              - name: openstack/ceilometer
                override-checkout: stable/zed
              - name: openstack/neutron
                override-checkout: stable/zed
              - name: x/networking-l2gw
                override-checkout: stable/wallaby
              - name: openstack/networking-sfc
                override-checkout: stable/zed
              - name: openstack/networking-bgpvpn
                override-checkout: stable/zed
        - openstack-tox-docs:
            required-projects: *odl_doc_required_projects
        - openstack-tox-py38:
            required-projects: *odl_required_projects
        - openstack-tox-py39:
            required-projects: *odl_required_projects
        - openstack-tox-py310:
            required-projects: *odl_required_projects
        - networking-odl-rally-neon:
            voting: false
            irrelevant-files:
              - ^.*\.rst$
              - ^doc/.*$
              - ^releasenotes/.*$
        - networking-odl-rally-sodium:
            voting: false
            irrelevant-files:
              - ^.*\.rst$
              - ^doc/.*$
              - ^releasenotes/.*$
        - networking-odl-functional-neon:
            required-projects: *odl_required_projects
        - networking-odl-functional-sodium:
            required-projects: *odl_required_projects
    gate:
      jobs:
        - openstack-tox-pep8:
            required-projects: *odl_doc_required_projects
        - openstack-tox-docs:
            required-projects: *odl_doc_required_projects
        - openstack-tox-py38:
            required-projects: *odl_required_projects
        - openstack-tox-py39:
            required-projects: *odl_required_projects
        - openstack-tox-py310:
            required-projects: *odl_required_projects
        - networking-odl-functional-neon:
            required-projects: *odl_required_projects
        - networking-odl-functional-sodium:
            required-projects: *odl_required_projects
    periodic-weekly:
      jobs:
        - openstack-tox-py39
        - networking-odl-functional-sodium
