- project:
    templates:
      - openstack-python3-wallaby-jobs-neutron
      - release-notes-jobs-python3
      - periodic-stable-jobs-neutron
      - publish-openstack-docs-pti
      - check-requirements
    check:
      jobs:
        - openstack-tox-pep8:
            required-projects:
              - name: openstack/ceilometer
                override-checkout: stable/wallaby
              - name: x/networking-l2gw
                override-checkout: stable/wallaby
              - name: openstack/networking-sfc
                override-checkout: stable/wallaby
              - name: openstack/networking-bgpvpn
                override-checkout: stable/wallaby
        - openstack-tox-cover:
            required-projects:
              - name: openstack/ceilometer
                override-checkout: stable/wallaby
              - name: openstack/neutron
                override-checkout: stable/wallaby
              - name: x/networking-l2gw
                override-checkout: stable/wallaby
              - name: openstack/networking-sfc
                override-checkout: stable/wallaby
              - name: openstack/networking-bgpvpn
                override-checkout: stable/wallaby
        - openstack-tox-docs:
            required-projects:
              - name: openstack/ceilometer
                override-checkout: stable/wallaby
              - name: x/networking-l2gw
                override-checkout: stable/wallaby
              - name: openstack/networking-sfc
                override-checkout: stable/wallaby
              - name: openstack/networking-bgpvpn
                override-checkout: stable/wallaby
        - openstack-tox-py36:
            required-projects:
              - name: openstack/ceilometer
                override-checkout: stable/wallaby
              - name: x/networking-l2gw
                override-checkout: stable/wallaby
              - name: openstack/networking-sfc
                override-checkout: stable/wallaby
              - name: openstack/networking-bgpvpn
                override-checkout: stable/wallaby
        - openstack-tox-py38:
            required-projects:
              - name: openstack/ceilometer
                override-checkout: stable/wallaby
              - name: x/networking-l2gw
                override-checkout: stable/wallaby
              - name: openstack/networking-sfc
                override-checkout: stable/wallaby
              - name: openstack/networking-bgpvpn
                override-checkout: stable/wallaby
        - openstack-tox-py39:
            required-projects:
              - name: openstack/ceilometer
                override-checkout: stable/wallaby
              - name: x/networking-l2gw
                override-checkout: stable/wallaby
              - name: openstack/networking-sfc
                override-checkout: stable/wallaby
              - name: openstack/networking-bgpvpn
                override-checkout: stable/wallaby
        - networking-odl-rally-neon:
            voting: false
            irrelevant-files:
              - ^.*\.rst$
              - ^doc/.*$
              - ^releasenotes/.*$
        - networking-odl-rally-sodium:
            voting: false
            irrelevant-files:
              - ^.*\.rst$
              - ^doc/.*$
              - ^releasenotes/.*$
    gate:
      jobs:
        - openstack-tox-pep8:
            required-projects:
              - name: openstack/ceilometer
                override-checkout: stable/wallaby
              - name: x/networking-l2gw
                override-checkout: stable/wallaby
              - name: openstack/networking-sfc
                override-checkout: stable/wallaby
              - name: openstack/networking-bgpvpn
                override-checkout: stable/wallaby
        - openstack-tox-docs:
            required-projects:
              - name: openstack/ceilometer
                override-checkout: stable/wallaby
              - name: x/networking-l2gw
                override-checkout: stable/wallaby
              - name: openstack/networking-sfc
                override-checkout: stable/wallaby
              - name: openstack/networking-bgpvpn
                override-checkout: stable/wallaby
        - openstack-tox-py36:
            required-projects:
              - name: openstack/ceilometer
                override-checkout: stable/wallaby
              - name: x/networking-l2gw
                override-checkout: stable/wallaby
              - name: openstack/networking-sfc
                override-checkout: stable/wallaby
              - name: openstack/networking-bgpvpn
                override-checkout: stable/wallaby
        - openstack-tox-py38:
            required-projects:
              - name: openstack/ceilometer
                override-checkout: stable/wallaby
              - name: x/networking-l2gw
                override-checkout: stable/wallaby
              - name: openstack/networking-sfc
                override-checkout: stable/wallaby
              - name: openstack/networking-bgpvpn
                override-checkout: stable/wallaby
        - openstack-tox-py39:
            required-projects:
              - name: openstack/ceilometer
                override-checkout: stable/wallaby
              - name: x/networking-l2gw
                override-checkout: stable/wallaby
              - name: openstack/networking-sfc
                override-checkout: stable/wallaby
              - name: openstack/networking-bgpvpn
                override-checkout: stable/wallaby
